version: '3'
services:
        nginx:
                build:
                        context: .
                        args:
                                - 'NGINX_HOST=/* Your domain here */'
                container_name: nginx
                restart: 'unless-stopped'
                ports:
                        - '80:80'
                        - '443:443'
                volumes:
                        - './nginx/nginx_secrets:/etc/letsencrypt'
                environment:
                        - 'CERTBOT_EMAIL=/* Your email here */' 
        backend:
                build: './backend'
                container_name: backend
                restart: 'on-failure:5'
                depends_on:
                        - mongodb
                expose:
                        - '3000'
                environment:
                        - 'PORT=3000'
                        - 'MONGO_URI=mongodb://root:Super-Hard-Password-Vp2NoUNduzLt982f@mongodb/template01?authSource=admin'

        mongodb:
                image: mongo
                container_name: mongo
                restart: 'unless-stopped'
                volumes: 
                        - 'mongodb:/data/db'
                environment:
                        - 'MONGO_INITDB_ROOT_USERNAME=root'
                        - 'MONGO_INITDB_ROOT_PASSWORD=Super-Hard-Password-Vp2NoUNduzLt982f'
                        - 'MONGO_INITDB_DATABASE=template01'
        
volumes:
        mongodb:
